In [1]:
import keras as kr
import pandas as pd
import sklearn.preprocessing as pre
import sklearn.model_selection as mod
import matplotlib.pyplot as plt

import pandas as pd
import numpy as np

from sklearn import datasets
from sklearn.utils import Bunch

from keras import models, layers

Using TensorFlow backend.


In [2]:
boston = datasets.load_boston()
type(boston)

sklearn.utils.Bunch

In [3]:
df = pd.DataFrame(data=boston['data'], columns=boston['feature_names'])
df['MEDV'] =boston['target']
medv = df['MEDV'].copy()
del df['MEDV']
df = pd.concat((medv, df), axis=1)

df

MEDV     CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    24.0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    21.6  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    34.7  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    33.4  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    36.2  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..    ...      ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  22.4  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  20.6  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  23.9  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  22.0  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  11.9  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 14 columns]

In [4]:
inputs = df[['CRIM', 'CHAS', 'RM', 'DIS', 'TAX', 'AGE', 'LSTAT']]
inputs

CRIM  CHAS     RM     DIS    TAX   AGE  LSTAT
0    0.00632   0.0  6.575  4.0900  296.0  65.2   4.98
1    0.02731   0.0  6.421  4.9671  242.0  78.9   9.14
2    0.02729   0.0  7.185  4.9671  242.0  61.1   4.03
3    0.03237   0.0  6.998  6.0622  222.0  45.8   2.94
4    0.06905   0.0  7.147  6.0622  222.0  54.2   5.33
..       ...   ...    ...     ...    ...   ...    ...
501  0.06263   0.0  6.593  2.4786  273.0  69.1   9.67
502  0.04527   0.0  6.120  2.2875  273.0  76.7   9.08
503  0.06076   0.0  6.976  2.1675  273.0  91.0   5.64
504  0.10959   0.0  6.794  2.3889  273.0  89.3   6.48
505  0.04741   0.0  6.030  2.5050  273.0  80.8   7.88

[506 rows x 7 columns]

In [5]:
outputs = df[['MEDV']]
outputs

MEDV
0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
..    ...
501  22.4
502  20.6
503  23.9
504  22.0
505  11.9

[506 rows x 1 columns]

## Neural Network

In [6]:
x_train, x_test, y_train, y_test = mod.train_test_split(inputs, outputs, test_size=0.4)

In [59]:
m = kr.models.Sequential()

m.add(kr.layers.Dense(30, input_dim=7, activation="relu"))
#m.add(kr.layers.Dense(20, activation="relu"))
#m.add(kr.layers.Dense(5, activation="relu"))
m.add(kr.layers.Dense(1, activation="relu"))

m.compile(loss="mean_squared_error", optimizer="adam")

In [60]:
m.fit(x_train,  y_train, epochs=500, batch_size=20)

Epoch 1/500
303/303 [==============================] - 1s 3ms/step - loss: 611.9982
Epoch 2/500
303/303 [==============================] - 0s 108us/step - loss: 360.9167
Epoch 3/500
303/303 [==============================] - 0s 63us/step - loss: 257.6620
Epoch 4/500
303/303 [==============================] - 0s 119us/step - loss: 245.6210
Epoch 5/500
303/303 [==============================] - 0s 122us/step - loss: 225.2809
Epoch 6/500
303/303 [==============================] - 0s 89us/step - loss: 217.1030
Epoch 7/500
303/303 [==============================] - 0s 89us/step - loss: 205.2838
Epoch 8/500
303/303 [==============================] - 0s 59us/step - loss: 197.1740
Epoch 9/500
303/303 [==============================] - 0s 59us/step - loss: 188.0065
Epoch 10/500
303/303 [==============================] - 0s 62us/step - loss: 178.2502
Epoch 11/500
303/303 [==============================] - 0s 59us/step - loss: 168.9834
Epoch 12/500
303/303 [==============================] - 0s 82

In [61]:
m.predict(x_test).round().T

array([[23., 21., 21., 25., 11., 16., 22., 38., 18., 28., 25., 44.,  6.,
        34., 22., 19., 35., 15., 21., 23., 16., 15., 27., 17., 25., 15.,
        15., 36., 20., 28., 12., 27., 22., 15., 15., 42., 33., 17., 17.,
        15., 16., 32., 14., 16., 12., 18., 12., 15., 13., 29., 21., 10.,
        22., 24., 18., 51., 17.,  3., 20., 17., 49., 29., 18., 22., 20.,
         4., 20., 30., 18., 21., 19., 23., 26., 13., 19., 24., 16., 21.,
        11., 45., 27., 18., 13., 29.,  7., 17., 18., 15., 26., 23., 25.,
        26., 30., 41., 20., 10., 25., 17., 30., 20., 23., 31., 16., 16.,
        18., 31., 15., 17., 12., 16., 15., 25., 12., 22., 22., 22., 16.,
        23., 14., 42., 29., 16., 19., 27., 31., 19., 19., 22., 24., 23.,
        32., 19., 16., 27., 17., 20., 15., 17., 33., 24., 24., 31., 13.,
        17., 29., 18., 22., 24., 39., 24., 24., 39., 21., 12., 18., 31.,
        18., 16., 38., 21., 26., 14., 17., 26., 19., 22., 18., 25., 23.,
        18., 33., 27., 30., 18.,  6., 20., 16., 20.

In [62]:
y_test.as_matrix().astype(np.float32)

C:\Users\shaun\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[20.4],
       [19.9],
       [20.3],
       [22.9],
       [ 7. ],
       [13.3],
       [22. ],
       [32.4],
       [17.5],
       [25.1],
       [26.4],
       [50. ],
       [16.3],
       [37.2],
       [20.6],
       [20.1],
       [31.7],
       [15.4],
       [19.2],
       [24.8],
       [17.2],
       [16.2],
       [25. ],
       [16.7],
       [22.8],
       [13.9],
       [13.6],
       [34.9],
       [18.7],
       [22.1],
       [ 6.3],
       [30.1],
       [17. ],
       [13. ],
       [13.4],
       [44.8],
       [25. ],
       [16.2],
       [14.3],
       [15.4],
       [14.9],
       [31.2],
       [14.1],
       [23.2],
       [ 7.2],
       [16.4],
       [ 8.5],
       [19. ],
       [17.8],
       [31. ],
       [21. ],
       [12.3],
       [25. ],
       [33. ],
       [19.9],
       [21.9],
       [14.8],
       [ 8.8],
       [22.6],
       [15.2],
       [50. ],
       [26.6],
       [13.4],
       [22.3],
       [20.6],
       [17.9],
       [22

In [63]:
m.evaluate(x_test, y_test)

203/203 [==============================] - 0s 1ms/step


20.88518271892529

### Scaling of values

In [12]:
scaler = pre.StandardScaler()
scaler.fit(x_train)
xTrainScaled = scaler.transform(x_train)

In [49]:
m = kr.models.Sequential()

m.add(kr.layers.Dense(20, input_dim=7, activation="relu"))
#m.add(kr.layers.Dense(30, activation="relu"))
m.add(kr.layers.Dense(1, activation="relu"))

m.compile(loss="mean_squared_error", optimizer="adam")

In [51]:
m.fit(x_train, y_train, epochs=500,batch_size=20)

Epoch 1/500
303/303 [==============================] - 0s 56us/step - loss: 17.2865
Epoch 2/500
303/303 [==============================] - 0s 50us/step - loss: 17.5823
Epoch 3/500
303/303 [==============================] - 0s 62us/step - loss: 16.9356
Epoch 4/500
303/303 [==============================] - 0s 112us/step - loss: 18.8394
Epoch 5/500
303/303 [==============================] - 0s 62us/step - loss: 17.7608
Epoch 6/500
303/303 [==============================] - 0s 59us/step - loss: 17.4643
Epoch 7/500
303/303 [==============================] - 0s 56us/step - loss: 17.5168
Epoch 8/500
303/303 [==============================] - 0s 52us/step - loss: 18.0660
Epoch 9/500
303/303 [==============================] - 0s 49us/step - loss: 18.8343
Epoch 10/500
303/303 [==============================] - 0s 46us/step - loss: 18.2320
Epoch 11/500
303/303 [==============================] - 0s 48us/step - loss: 17.0990
Epoch 12/500
303/303 [==============================] - 0s 43us/step - lo

In [15]:
m.predict(x_test).round().T

array([[24., 23., 23., 25., 14., 16., 18., 33., 24., 30., 24., 38., 11.,
        30., 23., 22., 33., 18., 23., 25., 22., 18., 23., 20., 25., 14.,
        16., 31., 24., 24.,  9., 28., 23., 18., 15., 36., 27., 21., 20.,
        14., 20., 30., 18., 17., 10., 21., 16., 19.,  8., 27., 21., 12.,
        24., 34., 22., 37., 19.,  4., 22., 20., 41., 28., 13., 24., 23.,
         3., 19., 30., 18., 22., 23., 24., 26., 12., 22., 23., 21., 24.,
        13., 35., 28., 18., 17., 28.,  6., 17., 19., 17., 24., 28., 25.,
        29., 29., 36., 20.,  9., 27., 17., 26., 25., 26., 31., 19., 18.,
        21., 32., 20., 20., 18., 19., 13., 26.,  6., 21., 21., 20., 20.,
        25., 15., 36., 27., 19., 16., 29., 25., 21., 20., 25., 26., 22.,
        30., 16., 19., 28., 21., 22., 20., 15., 33., 22., 37., 33., 14.,
        19., 26., 22., 22., 24., 29., 27., 21., 32., 25.,  6., 22., 32.,
        17., 19., 37., 19., 28., 18., 19., 25., 20., 27., 27., 26., 19.,
        20., 30., 25., 28., 18.,  4., 16., 19., 24.

In [16]:
y_test.as_matrix().astype(np.float32)

C:\Users\shaun\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[20.4],
       [19.9],
       [20.3],
       [22.9],
       [ 7. ],
       [13.3],
       [22. ],
       [32.4],
       [17.5],
       [25.1],
       [26.4],
       [50. ],
       [16.3],
       [37.2],
       [20.6],
       [20.1],
       [31.7],
       [15.4],
       [19.2],
       [24.8],
       [17.2],
       [16.2],
       [25. ],
       [16.7],
       [22.8],
       [13.9],
       [13.6],
       [34.9],
       [18.7],
       [22.1],
       [ 6.3],
       [30.1],
       [17. ],
       [13. ],
       [13.4],
       [44.8],
       [25. ],
       [16.2],
       [14.3],
       [15.4],
       [14.9],
       [31.2],
       [14.1],
       [23.2],
       [ 7.2],
       [16.4],
       [ 8.5],
       [19. ],
       [17.8],
       [31. ],
       [21. ],
       [12.3],
       [25. ],
       [33. ],
       [19.9],
       [21.9],
       [14.8],
       [ 8.8],
       [22.6],
       [15.2],
       [50. ],
       [26.6],
       [13.4],
       [22.3],
       [20.6],
       [17.9],
       [22

In [17]:
m.evaluate(x_test, y_test)

203/203 [==============================] - 0s 325us/step


28.466322095523328

### Whiten the data

In [18]:
import sklearn.decomposition as dec

In [19]:
pca = dec.PCA(n_components=7, whiten=True)
pca.fit(inputs)
inputsWhite = pd.DataFrame(pca.transform(inputs), columns=inputs.columns)
inputsWhite 

CRIM      CHAS        RM       DIS       TAX       AGE     LSTAT
0   -0.663509 -0.233272 -0.293021  1.050929 -0.096252  0.481043 -0.427461
1   -0.973593 -1.004048 -0.009389  0.506824  0.940567  0.314973 -0.381295
2   -0.983348 -0.258292 -0.067823  1.105325  0.317847 -0.548717 -0.453840
3   -1.108941  0.296040  0.101933  0.977274  0.551310 -0.198596 -0.325939
4   -1.104338 -0.055755  0.132378  0.708171  0.843935 -0.727933 -0.347419
..        ...       ...       ...       ...       ...       ...       ...
501 -0.796080 -0.500752 -0.029251  0.250273 -1.215934 -0.143922 -0.503769
502 -0.792289 -0.806486 -0.118435  0.504609 -1.079397  0.881016 -0.499200
503 -0.785489 -1.370114 -0.378540  1.440893 -0.638801 -0.092065 -0.691366
504 -0.786237 -1.304799 -0.323375  1.251081 -0.538141  0.110392 -0.641559
505 -0.790376 -0.966634 -0.201473  0.806949 -0.763413  1.247897 -0.503949

[506 rows x 7 columns]

In [41]:
model = kr.models.Sequential()

model.add(kr.layers.Dense(20, input_dim=7, activation="relu"))
model.add(kr.layers.Dense(10, activation="linear"))
#model.add(kr.layers.Dense(10, activation="linear"))
model.add(kr.layers.Dense(1, activation="linear"))

model.compile(loss="mean_squared_error", optimizer="adam")


In [42]:
model.fit(inputsWhite, outputs, epochs=500, batch_size=10)

Epoch 1/500
506/506 [==============================] - 1s 1ms/step - loss: 574.3255
Epoch 2/500
506/506 [==============================] - 0s 168us/step - loss: 503.3362
Epoch 3/500
506/506 [==============================] - 0s 218us/step - loss: 398.5602
Epoch 4/500
506/506 [==============================] - 0s 189us/step - loss: 259.8464
Epoch 5/500
506/506 [==============================] - 0s 203us/step - loss: 129.0918
Epoch 6/500
506/506 [==============================] - 0s 201us/step - loss: 57.5798
Epoch 7/500
506/506 [==============================] - 0s 197us/step - loss: 34.9023
Epoch 8/500
506/506 [==============================] - 0s 202us/step - loss: 28.2866
Epoch 9/500
506/506 [==============================] - 0s 203us/step - loss: 25.0443
Epoch 10/500
506/506 [==============================] - 0s 203us/step - loss: 23.2013
Epoch 11/500
506/506 [==============================] - 0s 197us/step - loss: 22.0407
Epoch 12/500
506/506 [==============================] - 0s 1

In [22]:
model.predict(inputsWhite)

array([[28.408783 ],
       [24.086552 ],
       [34.243042 ],
       [32.28764  ],
       [32.36483  ],
       [25.402122 ],
       [16.971085 ],
       [17.548323 ],
       [15.93899  ],
       [16.239902 ],
       [20.292643 ],
       [16.348131 ],
       [19.591276 ],
       [20.343626 ],
       [19.929556 ],
       [19.852985 ],
       [22.98338  ],
       [16.653177 ],
       [18.774279 ],
       [17.590801 ],
       [10.914636 ],
       [17.229788 ],
       [15.678651 ],
       [12.563755 ],
       [15.23758  ],
       [12.436807 ],
       [14.984212 ],
       [15.429594 ],
       [22.318136 ],
       [24.294474 ],
       [12.280963 ],
       [18.316982 ],
       [17.78784  ],
       [12.744481 ],
       [14.606876 ],
       [21.572956 ],
       [20.034315 ],
       [21.749926 ],
       [22.623991 ],
       [29.50036  ],
       [34.646263 ],
       [31.096006 ],
       [25.965897 ],
       [26.029861 ],
       [20.821005 ],
       [19.493332 ],
       [20.178886 ],
       [17.81

In [52]:
model.predict(inputsWhite).T - outputs.as_matrix()

C:\Users\shaun\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[  0.82231903,  -2.45430183,  10.1337204 , ...,   6.33987808,
          3.44156075,  -4.47255325],
       [  3.22231903,  -0.05430183,  12.5337204 , ...,   8.73987808,
          5.84156075,  -2.07255325],
       [ -9.87768097, -13.15430183,  -0.5662796 , ...,  -4.36012192,
         -7.25843925, -15.17255325],
       ...,
       [  0.92231903,  -2.35430183,  10.2337204 , ...,   6.43987808,
          3.54156075,  -4.37255325],
       [  2.82231903,  -0.45430183,  12.1337204 , ...,   8.33987808,
          5.44156075,  -2.47255325],
       [ 12.92231903,   9.64569817,  22.2337204 , ...,  18.43987808,
         15.54156075,   7.62744675]])

In [53]:
np.sum((model.predict(inputsWhite).T - outputs.as_matrix())**2)

C:\Users\shaun\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


41486050.14914558

In [54]:
np.sqrt(np.sum((model.predict(inputsWhite).T - outputs.as_matrix())**2))

C:\Users\shaun\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


6440.966553953342

In [55]:
m.evaluate(inputsWhite, outputs)

506/506 [==============================] - 0s 403us/step


435.2889208887877