In [1]:
import keras as kr
import pandas as pd
import sklearn.preprocessing as pre
import sklearn.model_selection as mod
import matplotlib.pyplot as plt

import pandas as pd
import numpy as np

from sklearn import datasets
from sklearn.utils import Bunch

from keras import models, layers

Using TensorFlow backend.


In [2]:
boston = datasets.load_boston()
type(boston)

sklearn.utils.Bunch

In [3]:
df = pd.DataFrame(data=boston['data'], columns=boston['feature_names'])
df['MEDV'] =boston['target']
medv = df['MEDV'].copy()
del df['MEDV']
df = pd.concat((medv, df), axis=1)

df

MEDV     CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    24.0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    21.6  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    34.7  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    33.4  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    36.2  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..    ...      ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  22.4  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  20.6  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  23.9  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  22.0  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  11.9  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 14 columns]

In [4]:
inputs = df[['CRIM', 'CHAS', 'RM', 'DIS', 'TAX', 'AGE', 'LSTAT']]
inputs

CRIM  CHAS     RM     DIS    TAX   AGE  LSTAT
0    0.00632   0.0  6.575  4.0900  296.0  65.2   4.98
1    0.02731   0.0  6.421  4.9671  242.0  78.9   9.14
2    0.02729   0.0  7.185  4.9671  242.0  61.1   4.03
3    0.03237   0.0  6.998  6.0622  222.0  45.8   2.94
4    0.06905   0.0  7.147  6.0622  222.0  54.2   5.33
..       ...   ...    ...     ...    ...   ...    ...
501  0.06263   0.0  6.593  2.4786  273.0  69.1   9.67
502  0.04527   0.0  6.120  2.2875  273.0  76.7   9.08
503  0.06076   0.0  6.976  2.1675  273.0  91.0   5.64
504  0.10959   0.0  6.794  2.3889  273.0  89.3   6.48
505  0.04741   0.0  6.030  2.5050  273.0  80.8   7.88

[506 rows x 7 columns]

In [5]:
outputs = df[['MEDV']]
outputs

MEDV
0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
..    ...
501  22.4
502  20.6
503  23.9
504  22.0
505  11.9

[506 rows x 1 columns]

## Neural Network

In [6]:
x_train, x_test, y_train, y_test = mod.train_test_split(inputs, outputs, test_size=0.3)

In [7]:
m = kr.models.Sequential()

m.add(kr.layers.Dense(20, input_dim=7, activation="relu"))
m.add(kr.layers.Dense(1, activation="relu"))

m.compile(loss="mean_squared_error", optimizer="adam")

In [8]:
m.fit(x_train,  y_train, epochs=100, batch_size=10)




Epoch 1/100





354/354 [==============================] - 0s 406us/step - loss: 362.7064
Epoch 2/100
354/354 [==============================] - 0s 54us/step - loss: 273.2952
Epoch 3/100
354/354 [==============================] - 0s 54us/step - loss: 225.7217
Epoch 4/100
354/354 [==============================] - 0s 48us/step - loss: 199.5810
Epoch 5/100
354/354 [==============================] - 0s 51us/step - loss: 186.8047
Epoch 6/100
354/354 [==============================] - 0s 51us/step - loss: 178.5087
Epoch 7/100
354/354 [==============================] - 0s 51us/step - loss: 163.8384
Epoch 8/100
354/354 [==============================] - 0s 54us/step - loss: 154.3629
Epoch 9/100
354/354 [==============================] - 0s 56us/step - loss: 149.5947
Epoch 10/100
354/354 [==============================] - 0s 56us/step - loss: 140.0584
Epoch 11/100
354/354 [==============================] - 0s 56us/step - loss: 131.0486
Epoch 12/100
354/354 [==============================] 

In [9]:
m.predict(x_test).round().T

array([[25., 22., 26., 17., 22., 31., 24., 27., 19., 12.,  4., 26., 23.,
        22., 20., 21., 17., 30., 29., 26., 20., 27., 32., 35., 21., 26.,
        27., 22., 23., 32., 18., 25., 24., 26., 24., 27.,  8., 23., 28.,
        29., 24., 20., 18., 26., 18., 14., 24., 22., 27., 12., 21., 23.,
        27., 22., 34., 24., 35., 33., 22., 19., 27., 24., 23., 22., 22.,
        26., 20., 30., 21., 29., 21.,  0., 23., 13., 16., 28., 32., 30.,
         4., 33., 21., 16., 25., 18., 19., 18., 20., 22., 32., 23., 12.,
        22., 22., 27., 29., 24., 28., 20., 26., 20., 23., 15., 25., 35.,
        21., 33., 16., 28., 18., 19., 30., 28., 33., 20., 25., 20., 21.,
        18., 23., 22., 19., 42., 13., 19., 24., 28., 24., 23., 29., 13.,
         7., 22., 34., 28., 11., 24., 20., 24., 22.,  6., 18., 22.,  2.,
        28., 21., 37., 17., 25., 17., 19., 23., 17.]], dtype=float32)

In [10]:
y_test.as_matrix().astype(np.float32)

C:\Users\shaun\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[25.3],
       [19.5],
       [24.4],
       [12.7],
       [24. ],
       [22.9],
       [20.1],
       [22.3],
       [20.8],
       [13.1],
       [10.2],
       [23.8],
       [21.5],
       [18.2],
       [19.3],
       [15.2],
       [13.3],
       [20.5],
       [32. ],
       [36.1],
       [11.7],
       [22.7],
       [37. ],
       [45.4],
       [15.2],
       [29.8],
       [19.8],
       [20.3],
       [19.3],
       [22.2],
       [15.1],
       [22. ],
       [20.8],
       [24.8],
       [17.2],
       [22.2],
       [ 9.7],
       [21.4],
       [26.6],
       [50. ],
       [21.1],
       [14.3],
       [13.6],
       [18.9],
       [21.8],
       [10.2],
       [20.6],
       [24.4],
       [27.5],
       [12.8],
       [20. ],
       [18.9],
       [25. ],
       [29.6],
       [29.6],
       [30.7],
       [37.9],
       [26.6],
       [18.1],
       [20.3],
       [31.5],
       [20.4],
       [16.8],
       [17.8],
       [23.8],
       [24.2],
       [14

In [11]:
m.evaluate(x_test, y_test)

152/152 [==============================] - 0s 112us/step


27.393136676989105

### Scaling of values

In [12]:
scaler = pre.StandardScaler()
scaler.fit(x_train)
xTrainScaled = scaler.transform(x_train)

In [13]:
m = kr.models.Sequential()

m.add(kr.layers.Dense(20, input_dim=7, activation="linear"))
m.add(kr.layers.Dense(30, activation="relu"))
m.add(kr.layers.Dense(1, activation="relu"))

m.compile(loss="mean_squared_error", optimizer="adam")

In [14]:
m.fit(x_train, y_train, epochs=100,batch_size=15)

Epoch 1/100
354/354 [==============================] - 0s 468us/step - loss: 624.3823
Epoch 2/100
354/354 [==============================] - 0s 45us/step - loss: 624.3823
Epoch 3/100
354/354 [==============================] - 0s 45us/step - loss: 624.3823
Epoch 4/100
354/354 [==============================] - 0s 45us/step - loss: 624.3823
Epoch 5/100
354/354 [==============================] - 0s 39us/step - loss: 624.3823
Epoch 6/100
354/354 [==============================] - 0s 42us/step - loss: 624.3823
Epoch 7/100
354/354 [==============================] - 0s 37us/step - loss: 624.3823
Epoch 8/100
354/354 [==============================] - 0s 42us/step - loss: 624.3823
Epoch 9/100
354/354 [==============================] - 0s 42us/step - loss: 624.3823
Epoch 10/100
354/354 [==============================] - 0s 42us/step - loss: 624.3823
Epoch 11/100
354/354 [==============================] - 0s 39us/step - loss: 624.3823
Epoch 12/100
354/354 [==============================] - 0s 42u

In [15]:
m.predict(x_test).round().T

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [16]:
y_test.as_matrix().astype(np.float32)

C:\Users\shaun\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[25.3],
       [19.5],
       [24.4],
       [12.7],
       [24. ],
       [22.9],
       [20.1],
       [22.3],
       [20.8],
       [13.1],
       [10.2],
       [23.8],
       [21.5],
       [18.2],
       [19.3],
       [15.2],
       [13.3],
       [20.5],
       [32. ],
       [36.1],
       [11.7],
       [22.7],
       [37. ],
       [45.4],
       [15.2],
       [29.8],
       [19.8],
       [20.3],
       [19.3],
       [22.2],
       [15.1],
       [22. ],
       [20.8],
       [24.8],
       [17.2],
       [22.2],
       [ 9.7],
       [21.4],
       [26.6],
       [50. ],
       [21.1],
       [14.3],
       [13.6],
       [18.9],
       [21.8],
       [10.2],
       [20.6],
       [24.4],
       [27.5],
       [12.8],
       [20. ],
       [18.9],
       [25. ],
       [29.6],
       [29.6],
       [30.7],
       [37.9],
       [26.6],
       [18.1],
       [20.3],
       [31.5],
       [20.4],
       [16.8],
       [17.8],
       [23.8],
       [24.2],
       [14

In [17]:
m.evaluate(x_test, y_test)

152/152 [==============================] - 0s 184us/step


517.0723619962994